# SPDX-FileCopyrightText: 2021 Diego Elio Pettenò
#
# SPDX-License-Identifier: 0BSD

# Note: this is intended as a package config that can be included on a device
# configuration file.
#
# It takes the following substitutions, for example:
#
# substitutions:
#   node_name: "study-climate"
#   device_verbose_name: "Study Climate"
#   reference_temperature: sensor.study_average_temperature

esphome:
  name: ${node_name}
  friendly_name: ${device_verbose_name}

  includes:
    - lg-pqrcuds0.h

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    version: recommended

uart:
  - id: wall_uart
    tx_pin: GPIO25
    rx_pin: GPIO26
    baud_rate: 104

sensor:
  - id: reference_temperature
    platform: homeassistant
    internal: true
    entity_id: ${reference_temperature}

climate:
  - platform: custom
    lambda: |-
      auto lg_pqrcuds0 = new LgHvac(id(wall_uart), id(reference_temperature));
      App.register_component(lg_pqrcuds0);
      return {lg_pqrcuds0};

    climates:
      - name: Climate
